FROM python:3.9-slim

# 安装系统依赖
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cron openssl libssl-dev gcc && \
    rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制代码和配置
COPY ./app/requirements.txt .
COPY ./app/main.py .
COPY ./config/cron_job /etc/cron.d/weather-cron

# 安装Python依赖
RUN pip install --no-cache-dir -r requirements.txt

# 设置定时任务权限
RUN chmod 0644 /etc/cron.d/weather-cron && \
    touch /var/log/cron.log

# 初始化容器启动命令
CMD ["sh", "-c", "cron && tail -f /var/log/cron.log"]